funni vestine recipe. Intended to be annoying, esp for ghetto chemming
Prison-Station-14/prison-station-14 pull request #12
Opened 2024-07-15 20:38 UTC by Lyroth001

## About the PR
Adds a recipe for vestine - designed to be annoying for ghetto chemming
1 Siderlac
1 Diphenylmethylamine
3 Whiskey
20 Razorium (catalyst)

## Why / Balance
So non-traitor prisoners can use vestine requiring chems in escape attempts, if they are willing to put in the time for it.
Siderlac - requires either working in botany and 'borrowing' some product or stealing/begging it
Diphenylmethylamine - long chain of rquired chems, esp annoying without chemmaster
Raz catalyst - leaves sharp bits in your vestine, this is either nice if your making stuff that you arent taking or a major downside for like. Stimulants

## Technical details
Recipe added to bottom of chemical recipes

2024-07-15 23:58 UTC, Lyroth001 commented
Original intention was 2 bic 3 punc, current is more dangerous. Could probably do original tbh, didnt know how before i made the pr tho

2024-07-16 00:13 UTC, Lyroth001 commented
this is now how it does it

2024-07-18 08:13 UTC, Truoizys commented
Good shit. could you move the changes to a seperate YAML file in a SP14 directory, just so our changes are recognisable from upstream thaaanks.

might hold off on merging until we have the maps out? might also change my mind?

2024-07-18 08:20 UTC, Truoizys requested changes
move changes to /Reactions/SP14/chemicals.yml

2024-08-07 16:12 UTC, Truoizys approved these changes
All good! probably will keep it on postpone till we're closer to playtests but its a-ok for merging

2025-06-02 11:27 UTC, closed without merging